### ISSUE TITLE
Repository is empty 

### ISSUE THREAD

**Issue by tobischi** [red6/groove-your-jenkins#1]
Dear red6, 

just read the article "Groove your Jenkins" in Java Magazin 8/2016. There is a link pointing here but here is nothing. 

Could you please provide our restore the content? 

Sincerely, 
tobischi.

**Comment by remast** [comment]
Sorry we had the code in our own repo and forgot to push it to github. It's there now!

**Comment by tobischi** [comment]
Great thanks for resolving so quickly!
